import streamlit as st
import numpy as np
import tensorflow as tf
from PIL import Image

# =============================
# Page Config
# =============================
st.set_page_config(
    page_title="Skin Disease Classification",
    layout="centered"
)

st.title("🧴 Skin Disease Classification using AI")

# =============================
# Load Model
# =============================
@st.cache_resource
def load_model():
    model = tf.keras.models.load_model("skin_disease_model.h5")
    return model

model = load_model()

# =============================
# Class Labels
# =============================
class_labels = {
    0: "Actinic Keratoses (akiec)",
    1: "Basal Cell Carcinoma (bcc)",
    2: "Benign Keratosis (bkl)",
    3: "Dermatofibroma (df)",
    4: "Melanoma (mel)",
    5: "Melanocytic Nevus (nv)",
    6: "Vascular Lesion (vasc)"
}

# =============================
# Upload Image
# =============================
uploaded_file = st.file_uploader(
    "📤 Upload a skin image",
    type=["jpg", "jpeg", "png"]
)

if uploaded_file is not None:

    # Display Image
    image = Image.open(uploaded_file).convert("RGB")
    st.image(image, caption="Uploaded Image", use_column_width=True)

    # =============================
    # Preprocess Image
    # =============================
    img = image.resize((64, 64))
    img_array = np.array(img) / 255.0
    img_array = np.expand_dims(img_array, axis=0)

    # =============================
    # Prediction
    # =============================
    predictions = model.predict(img_array)

    predicted_class = np.argmax(predictions)
    confidence = np.max(predictions) * 100

    disease_name = class_labels[predicted_class]

    # =============================
    # Result Display
    # =============================
    st.success(f"✅ Prediction: **{disease_name}**")
    st.info(f"🔎 Confidence: **{confidence:.2f}%**")

    # =============================
    # Disclaimer
    # =============================
    st.warning(
        "⚠️ This prediction is generated by an AI model and is not a medical diagnosis. "
        "Please consult a qualified dermatologist for professional advice."
    )


